#pragma checksum "..\..\..\Dialog\MakeGame.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3E49834E9CC1B435787B49C1F5FAA16E595AA08F"
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Gra_Państwa_Miasta.Dialog {
    
    
    /// <summary>
    /// MakeGame
    /// </summary>
    public partial class MakeGame : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MainGrid;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox NameOfNewGame;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AdressOfNewGame;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PortOfNewGame;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox KolumnyCheck;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Kolumny;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox PanstwoCheck;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox MistoCheck;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ZwierzeCheck;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox RoslinaCheck;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox RzeczCheck;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ImieCheck;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Czas;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CzasGrid;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CzasRundyCheck;
        
        #line default
        #line hidden
        
        
        #line 120 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CzasRundy;
        
        #line default
        #line hidden
        
        
        #line 121 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CzasRundyText;
        
        #line default
        #line hidden
        
        
        #line 124 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CzasGryCheck;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CzasGry;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Rundy;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Punkty;
        
        #line default
        #line hidden
        
        
        #line 141 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox IloscPunktowDoWygranej;
        
        #line default
        #line hidden
        
        
        #line 142 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock IloscPunktowDoWygranejText;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox Dogrywka;
        
        #line default
        #line hidden
        
        
        #line 151 "..\..\..\Dialog\MakeGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Make;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Gra Państwa Miasta;component/dialog/makegame.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Dialog\MakeGame.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.MainGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.NameOfNewGame = ((System.Windows.Controls.TextBox)(target));
            
            #line 27 "..\..\..\Dialog\MakeGame.xaml"
            this.NameOfNewGame.PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.NameOfNewGame_MouseDown);
            
            #line default
            #line hidden
            
            #line 27 "..\..\..\Dialog\MakeGame.xaml"
            this.NameOfNewGame.LostFocus += new System.Windows.RoutedEventHandler(this.NameOfNewGame_LostFocus);
            
            #line default
            #line hidden
            return;
            case 3:
            this.AdressOfNewGame = ((System.Windows.Controls.TextBlock)(target));
            
            #line 41 "..\..\..\Dialog\MakeGame.xaml"
            this.AdressOfNewGame.PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.NameOfNewGame_MouseDown);
            
            #line default
            #line hidden
            
            #line 41 "..\..\..\Dialog\MakeGame.xaml"
            this.AdressOfNewGame.LostFocus += new System.Windows.RoutedEventHandler(this.NameOfNewGame_LostFocus);
            
            #line default
            #line hidden
            return;
            case 4:
            this.PortOfNewGame = ((System.Windows.Controls.TextBox)(target));
            
            #line 42 "..\..\..\Dialog\MakeGame.xaml"
            this.PortOfNewGame.PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.PortOfNewGame_OnPreviewMouseDown);
            
            #line default
            #line hidden
            
            #line 42 "..\..\..\Dialog\MakeGame.xaml"
            this.PortOfNewGame.LostFocus += new System.Windows.RoutedEventHandler(this.PortOfNewGame_OnLostFocus);
            
            #line default
            #line hidden
            return;
            case 5:
            this.KolumnyCheck = ((System.Windows.Controls.CheckBox)(target));
            
            #line 50 "..\..\..\Dialog\MakeGame.xaml"
            this.KolumnyCheck.Click += new System.Windows.RoutedEventHandler(this.KolumnyCheck_OnClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.Kolumny = ((System.Windows.Controls.Grid)(target));
            return;
            case 7:
            this.PanstwoCheck = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 8:
            this.MistoCheck = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 9:
            this.ZwierzeCheck = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 10:
            this.RoslinaCheck = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 11:
            this.RzeczCheck = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 12:
            this.ImieCheck = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 13:
            this.Czas = ((System.Windows.Controls.CheckBox)(target));
            
            #line 107 "..\..\..\Dialog\MakeGame.xaml"
            this.Czas.Click += new System.Windows.RoutedEventHandler(this.CzasCheck_OnClick);
            
            #line default
            #line hidden
            return;
            case 14:
            this.CzasGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 15:
            this.CzasRundyCheck = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 16:
            this.CzasRundy = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.CzasRundyText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.CzasGryCheck = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 19:
            this.CzasGry = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.Rundy = ((System.Windows.Controls.CheckBox)(target));
            
            #line 132 "..\..\..\Dialog\MakeGame.xaml"
            this.Rundy.Click += new System.Windows.RoutedEventHandler(this.KolumnyCheck_OnClick);
            
            #line default
            #line hidden
            return;
            case 21:
            this.Punkty = ((System.Windows.Controls.CheckBox)(target));
            
            #line 138 "..\..\..\Dialog\MakeGame.xaml"
            this.Punkty.Click += new System.Windows.RoutedEventHandler(this.KolumnyCheck_OnClick);
            
            #line default
            #line hidden
            return;
            case 22:
            this.IloscPunktowDoWygranej = ((System.Windows.Controls.TextBox)(target));
            return;
            case 23:
            this.IloscPunktowDoWygranejText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 24:
            this.Dogrywka = ((System.Windows.Controls.CheckBox)(target));
            
            #line 145 "..\..\..\Dialog\MakeGame.xaml"
            this.Dogrywka.Click += new System.Windows.RoutedEventHandler(this.KolumnyCheck_OnClick);
            
            #line default
            #line hidden
            return;
            case 25:
            this.Make = ((System.Windows.Controls.Button)(target));
            
            #line 151 "..\..\..\Dialog\MakeGame.xaml"
            this.Make.Click += new System.Windows.RoutedEventHandler(this.Create_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

